% Camera Calibration Script
% Most of this script is generated, but a few things were modified to make it 
% nicer to run. For example, a DEBUG flag was added so the script will not
% generate figures unless absolutely needed!


if exist('DEBUG', 'var') ~= 1
    DEBUG = true;
end

% Define images to process
% Note: This WILL be different, make sure you replace these with your pictures before
imageFileNames = {'/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image21.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image22.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image23.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image24.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image25.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image26.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image27.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image28.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image29.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image30.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image31.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image32.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image33.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image34.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image35.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image36.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image37.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image38.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image39.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image40.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image41.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image42.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image43.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image44.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image45.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image46.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image47.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image48.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image49.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image50.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image51.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image52.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image53.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image54.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image55.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image56.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image57.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image58.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image59.png'...
    '/home/yongxiang/RBE3001_Matlab11/camera_calibration/Image60.png'...
};

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates of the corners of the squares
squareSize = 25;  % in units of 'millimeters'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

if DEBUG
    
    % View reprojection errors
    h1=figure; showReprojectionErrors(cameraParams);

    % Visualize pattern locations
    h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

    % Display parameter estimation errors
    displayErrors(estimationErrors, cameraParams);
    
end
